### ISSUE TITLE
Trouble viewing CARO tree in OLS

### ISSUE THREAD

**Issue by vanaukenk** [EBISPOT/OLS#324]
Hi,

I've been trying to use the OLS to view CARO terms, but am unable to get the tree view to load.

Here's one example:

https://www.ebi.ac.uk/ols/ontologies/caro/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCARO_0000000

The tree view for other ontologies (e.g. GO, PRO, UBERON) seem to be loading fine for me.

**Comment by henrietteharmse** [comment]
Hi @vanaukenk 

Thanks for reporting this. It seems in the CARO case this call triggers an exception, hence the reason for it not displaying correctly.

A possible workaround till we have a fix for this may be to navigate to CARO_000000, i.e. from https://www.ebi.ac.uk/ols/ontologies/caro
navigate as follows: 
`entity->continuant->independent continuant->biological entity->anatomical entity`
However, clicking on `anatomical entity` or any of it children will trigger this error.




For reference here is the exception that is triggered:
```
2020-02-20 14:58:49.687 DEBUG 5065 --- [http-nio-8480-exec-1] u.a.e.s.o.n.s.AbstractJsTreeBuilder      : Return isRootNode = false
2020-02-20 14:58:49.687 DEBUG 5065 --- [http-nio-8480-exec-1] u.a.e.s.o.n.s.AbstractJsTreeBuilder      : Return isRootNode = false
2020-02-20 14:58:49.687 DEBUG 5065 --- [http-nio-8480-exec-1] u.a.e.s.o.n.s.AbstractJsTreeBuilder      : nodeId = 12370117
2020-02-20 14:58:49.687 DEBUG 5065 --- [http-nio-8480-exec-1] u.a.e.s.o.n.s.AbstractJsTreeBuilder      : viewMode = ALL
2020-02-20 14:58:49.687 DEBUG 5065 --- [http-nio-8480-exec-1] u.a.e.s.o.n.s.AbstractJsTreeBuilder      : Return isRootNode = false
2020-02-20 14:58:49.687 DEBUG 5065 --- [http-nio-8480-exec-1] u.a.e.s.o.n.s.AbstractJsTreeBuilder      : Return isRootNode = false
2020-02-20 14:58:49.687 DEBUG 5065 --- [http-nio-8480-exec-1] u.a.e.s.o.n.s.AbstractJsTreeBuilder      : nodeId = 12370133
2020-02-20 14:58:49.687 DEBUG 5065 --- [http-nio-8480-exec-1] u.a.e.s.o.n.s.AbstractJsTreeBuilder      : viewMode = ALL
2020-02-20 14:58:49.687 DEBUG 5065 --- [http-nio-8480-exec-1] u.a.e.s.o.n.s.AbstractJsTreeBuilder      : Return isRootNode = false
2020-02-20 14:58:49.687 DEBUG 5065 --- [http-nio-8480-exec-1] u.a.e.s.o.n.s.AbstractJsTreeBuilder      : Return isRootNode = false
2020-02-20 14:58:49.687 DEBUG 5065 --- [http-nio-8480-exec-1] u.a.e.s.o.n.s.AbstractJsTreeBuilder      : nodeId = 12370302
2020-02-20 14:58:49.687 DEBUG 5065 --- [http-nio-8480-exec-1] u.a.e.s.o.n.s.AbstractJsTreeBuilder      : viewMode = ALL
2020-02-20 14:58:49.688 DEBUG 5065 --- [http-nio-8480-exec-1] u.a.e.s.o.n.s.AbstractJsTreeBuilder      : Return isRootNode = false
2020-02-20 14:58:49.688 DEBUG 5065 --- [http-nio-8480-exec-1] u.a.e.s.o.n.s.AbstractJsTreeBuilder      : Return isRootNode = false
2020-02-20 14:58:49.688 DEBUG 5065 --- [http-nio-8480-exec-1] u.a.e.s.o.n.s.AbstractJsTreeBuilder      : nodeId = 12370296
2020-02-20 14:58:49.688 DEBUG 5065 --- [http-nio-8480-exec-1] u.a.e.s.o.n.s.AbstractJsTreeBuilder      : viewMode = ALL
2020-02-20 14:58:49.688 DEBUG 5065 --- [http-nio-8480-exec-1] u.a.e.s.o.n.s.AbstractJsTreeBuilder      : Return isRootNode = false
2020-02-20 14:58:49.688 DEBUG 5065 --- [http-nio-8480-exec-1] u.a.e.s.o.n.s.AbstractJsTreeBuilder      : Return isRootNode = false
2020-02-20 14:58:49.688 DEBUG 5065 --- [http-nio-8480-exec-1] u.a.e.s.o.n.s.AbstractJsTreeBuilder      : nodeId = 12370104
2020-02-20 14:58:49.688 DEBUG 5065 --- [http-nio-8480-exec-1] u.a.e.s.o.n.s.AbstractJsTreeBuilder      : viewMode = ALL
2020-02-20 14:58:49.688 DEBUG 5065 --- [http-nio-8480-exec-1] u.a.e.s.o.n.s.AbstractJsTreeBuilder      : Return isRootNode = false
2020-02-20 14:58:49.688 DEBUG 5065 --- [http-nio-8480-exec-1] u.a.e.s.o.n.s.AbstractJsTreeBuilder      : Return isRootNode = false
2020-02-20 14:58:49.688 DEBUG 5065 --- [http-nio-8480-exec-1] u.a.e.s.o.n.s.AbstractJsTreeBuilder      : nodeId = 12370117
2020-02-20 14:58:49.688 DEBUG 5065 --- [http-nio-8480-exec-1] u.a.e.s.o.n.s.AbstractJsTreeBuilder      : viewMode = ALL
2020-02-20 14:58:49.688 DEBUG 5065 --- [http-nio-8480-exec-1] u.a.e.s.o.n.s.AbstractJsTreeBuilder      : Return isRootNode = false
2020-02-20 14:58:49.688 DEBUG 5065 --- [http-nio-8480-exec-1] u.a.e.s.o.n.s.AbstractJsTreeBuilder      : Return isRootNode = false
2020-02-20 14:58:49.688 DEBUG 5065 --- [http-nio-8480-exec-1] u.a.e.s.o.n.s.AbstractJsTreeBuilder      : nodeId = 12370133
2020-02-20 14:58:49.688 DEBUG 5065 --- [http-nio-8480-exec-1] u.a.e.s.o.n.s.AbstractJsTreeBuilder      : viewMode = ALL
2020-02-20 14:58:49.688 DEBUG 5065 --- [http-nio-8480-exec-1] u.a.e.s.o.n.s.AbstractJsTreeBuilder      : Return isRootNode = false
2020-02-20 14:58:49.688 DEBUG 5065 --- [http-nio-8480-exec-1] u.a.e.s.o.n.s.AbstractJsTreeBuilder      : Return isRootNode = false

2020-02-20 14:58:49.692 ERROR 5065 --- [http-nio-8480-exec-1] o.s.boot.context.web.ErrorPageFilter     : Forwarding to error page from request [/api/ontologies/caro/terms/http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCARO_0000000/jstree] due to exception [null]

java.lang.StackOverflowError: null
        at sun.reflect.generics.parser.SignatureParser.parsePackageNameAndSimpleClassTypeSignature(SignatureParser.java:328)
        at sun.reflect.generics.parser.SignatureParser.parseClassTypeSignature(SignatureParser.java:310)
        at sun.reflect.generics.parser.SignatureParser.parseFieldTypeSignature(SignatureParser.java:289)
        at sun.reflect.generics.parser.SignatureParser.parseFieldTypeSignature(SignatureParser.java:283)
        at sun.reflect.generics.parser.SignatureParser.parseTypeSignature(SignatureParser.java:485)
        at sun.reflect.generics.parser.SignatureParser.parseZeroOrMoreTypeSignatures(SignatureParser.java:608)
        at sun.reflect.generics.parser.SignatureParser.parseFormalParameters(SignatureParser.java:585)
        at sun.reflect.generics.parser.SignatureParser.parseMethodTypeSignature(SignatureParser.java:576)
        at sun.reflect.generics.parser.SignatureParser.parseMethodSig(SignatureParser.java:171)
        at sun.reflect.generics.repository.ConstructorRepository.parse(ConstructorRepository.java:55)
        at sun.reflect.generics.repository.ConstructorRepository.parse(ConstructorRepository.java:43)
        at sun.reflect.generics.repository.AbstractRepository.<init>(AbstractRepository.java:74)
        at sun.reflect.generics.repository.GenericDeclRepository.<init>(GenericDeclRepository.java:49)
        at sun.reflect.generics.repository.ConstructorRepository.<init>(ConstructorRepository.java:51)
        at sun.reflect.generics.repository.ConstructorRepository.make(ConstructorRepository.java:69)
        at java.lang.reflect.Constructor.getGenericInfo(Constructor.java:87)
        at java.lang.reflect.Executable.getGenericParameterTypes(Executable.java:283)
        at java.lang.reflect.Constructor.getGenericParameterTypes(Constructor.java:234)
        at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.getGenericParameterType(AnnotatedConstructor.java:114)
        at com.fasterxml.jackson.databind.introspect.AnnotatedWithParams.getParameter(AnnotatedWithParams.java:118)
        at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._checkIfCreatorPropertyBased(BasicDeserializerFactory.java:599)
        at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._addDeserializerConstructors(BasicDeserializerFactory.java:422)
        at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:324)
        at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:254)
        at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.createMapDeserializer(BasicDeserializerFactory.java:1164)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:380)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:352)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
        at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
        at com.fasterxml.jackson.databind.DeserializationContext.findNonContextualValueDeserializer(DeserializationContext.java:451)
        at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer._findCustomDeser(UntypedObjectDeserializer.java:162)
        at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.resolve(UntypedObjectDeserializer.java:140)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:296)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
        at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
        at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:428)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:164)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:25)
        at com.fasterxml.jackson.databind.DeserializationContext.handleSecondaryContextualization(DeserializationContext.java:669)
        at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:466)
        at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3838)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3732)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2726)
        at uk.ac.ebi.spot.ols.neo4j.service.AbstractJsTreeBuilder.getJsObjectTree(AbstractJsTreeBuilder.java:312)
        at uk.ac.ebi.spot.ols.neo4j.service.AbstractJsTreeBuilder.getJsObjectTree(AbstractJsTreeBuilder.java:318)
        at uk.ac.ebi.spot.ols.neo4j.service.AbstractJsTreeBuilder.getJsObjectTree(AbstractJsTreeBuilder.java:318)
```

**Comment by henrietteharmse** [comment]
@zoependlington @paolaroncaglia @matentzn @twhetzel 
This bug basically causes the ontology tree to load forever the given term.
Are you by any chance aware of similar a similar problem with other terms? If so, please note it here. 
Thanks!

**Comment by vanaukenk** [comment]
Thank you @henrietteharmse 
Let me know if there's any other information that would be helpful.

**Comment by matentzn** [comment]
Hmm sounds like CARO is cyclic in a quite complex way (OLS handles normal cyclicity), something line A subclass B part C subclass A. Given that the release file relies on external imports (RO, some BFO), the CARO release is vulnerable to changes upstream. Maybe thats what caused it. It really needs a proper ODK release.. @mellybelly @dosumis

**Comment by henrietteharmse** [comment]
See related issue: https://github.com/EBISPOT/OLS/issues/310/

**Comment by matentzn** [comment]
Wont help much but for another project of mine I could break the cycle by deleting the following terms:

```
http://purl.obolibrary.org/obo/UBERON_0000465
http://purl.obolibrary.org/obo/CARO_0000000
http://purl.obolibrary.org/obo/CARO_0000003
http://purl.obolibrary.org/obo/CARO_0000006
http://purl.obolibrary.org/obo/CARO_0001008
http://purl.obolibrary.org/obo/CARO_0010000
http://purl.obolibrary.org/obo/CARO_0030000
http://purl.obolibrary.org/obo/UBERON_0000061
http://purl.obolibrary.org/obo/UBERON_0001062
http://purl.obolibrary.org/obo/UBERON_0010000
```

My suspicion is therefore that the cycle has something to do with those..

**Comment by udp** [comment]
PR opened, but needs testing with different ontologies to check I didn't break the tree view.
