### ISSUE TITLE
Unable to run ols-indexer.jar or ols-neo4j-app.jar

### ISSUE THREAD

**Issue by fmaclean** [EBISPOT/OLS#369]
After a clean install using `mvn clean install`

Ensuring MongoDB and Solr dockerised services are running at default ports (started using `./run_ols_background_services.sh`).  I have also tried with Solr and MongoDB running both locally.

When I run 

`java -Xmx2g -jar -Dspring.profiles.active=uberon ols-apps/ols-neo4j-app/target/ols-neo4j-app.jar`

I get the following error:
```
2020-05-26 14:59:09,030 INFO main GraphLoaderApplication.logStarting - Starting GraphLoaderApplication v3.2.1-SNAPSHOT on fmaclean-MBP with PID 4742 (/Users/fmaclean/Documents/OLS/ols-apps/ols-neo4j-app/target/ols-neo4j-app.jar started by fmaclean in /Users/fmaclean/Documents/OLS)
2020-05-26 14:59:09,033 DEBUG main GraphLoaderApplication.logStarting - Running with Spring Boot v1.3.8.RELEASE, Spring v4.2.8.RELEASE
2020-05-26 14:59:09,033 INFO main GraphLoaderApplication.logStartupProfileInfo - The following profiles are active: uberon
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (jar:file:/Users/fmaclean/Documents/OLS/ols-apps/ols-neo4j-app/target/ols-neo4j-app.jar!/lib/spring-core-4.2.8.RELEASE.jar!/) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2020-05-26 14:59:09,894 INFO main OLSEnv.getOLSHome - *** $OLS_HOME not set - defaulting to: /Users/fmaclean/.ols ***
2020-05-26 14:59:13,341 ERROR main SpringApplication.handleRunFailure - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoAppConfig': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: org.springframework.boot.autoconfigure.mongo.MongoProperties uk.ac.ebi.spot.ols.config.MongoAppConfig.properties; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spring.data.mongodb.CONFIGURATION_PROPERTIES': Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1218)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:778)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
	at uk.ac.ebi.spot.ols.GraphLoaderApplication.main(GraphLoaderApplication.java:47)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:104)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:61)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)```

```

I get the same error if I try to run ols-indexer.jar. I'm struggling to understand this stack trace.

Thanks for you time.

**Comment by udp** [comment]
Hi, which version of Java are you using?

    java -version

**Comment by fmaclean** [comment]
Java:
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.252-b09, mixed mode)

**Comment by udp** [comment]
We have not tested OLS with OpenJDK, so it might be worth trying Oracle JDK (1.8).  It could also be a version clash in Maven, in which case you could try clearing ~/.m2.

**Comment by fmaclean** [comment]
Sorry I am new to java, surely clearing the local m2 folder will remove the `build-fix` folder that is necessary now as`m2.neo4j.org/releases` has been deprecated?

**Comment by udp** [comment]
Yes, you would have to re-copy the fix.

**Comment by fmaclean** [comment]
Oracle JDK 1.8 works. Interestingly, in the dockerised version [1], they use openjdk 8, however this must be in an earlier version, as it doesn't have the build-fix fix.

Thanks for you help!

[1] https://github.com/MaastrichtUniversity/ols-docker/blob/master/Dockerfile
