### ISSUE TITLE
com.mongodb.MongoTimeoutException error.

### ISSUE THREAD

**Issue by DSRYU** [EBISPOT/OLS#377]
We are installing OLS with Docker version on my mac-book notebook.
If you are okay, please help us. 
When the below step executed, the installation version gave us the below error with com.mongodb.MongoTimeoutException.
Could you take a look for us?

Thanks in advance.

RUN java ${MEMORY_USE} -Dols.home=/opt/OLS -jar /opt/OLS/ols-apps/ols-loading-app/target/ols-indexer.jar

Caused by: org.springframework.dao.DataAccessResourceFailureException: Timed out after 10000 ms while waiting to connect. Client view of cluster state is {type=Unknown, servers=[{address=localhost:27017, type=Unknown, state=Connecting, exception={com.mongodb.MongoException$Network: Exception opening the socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 10000 ms while waiting to connect. Client view of cluster state is {type=Unknown, servers=[{address=localhost:27017, type=Unknown, state=Connecting, exception={com.mongodb.MongoException$Network: Exception opening the socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]
	at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:75)
	at org.springframework.data.mongodb.core.MongoTemplate.potentiallyConvertRuntimeException(MongoTemplate.java:2089)
	at org.springframework.data.mongodb.core.MongoTemplate.executeFindMultiInternal(MongoTemplate.java:1932)
	at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:1738)
	at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:1721)
	at org.springframework.data.mongodb.core.MongoTemplate.find(MongoTemplate.java:601)
	at org.springframework.data.mongodb.repository.support.SimpleMongoRepository.findAll(SimpleMongoRepository.java:268)
	at org.springframework.data.mongodb.repository.support.SimpleMongoRepository.findAll(SimpleMongoRepository.java:193)
	at org.springframework.data.mongodb.repository.support.SimpleMongoRepository.findAll(SimpleMongoRepository.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.executeMethodOn(RepositoryFactorySupport.java:483)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:468)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:440)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
	at com.sun.proxy.$Proxy63.findAll(Unknown Source)
	at uk.ac.ebi.spot.ols.service.MongoOntologyRepositoryService.getAllDocuments(MongoOntologyRepositoryService.java:40)
	at uk.ac.ebi.spot.ols.LoadingApplication.run(LoadingApplication.java:120)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:800)
	... 12 more
Caused by: com.mongodb.MongoTimeoutException: Timed out after 10000 ms while waiting to connect. Client view of cluster state is {type=Unknown, servers=[{address=localhost:27017, type=Unknown, state=Connecting, exception={com.mongodb.MongoException$Network: Exception opening the socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]
	at com.mongodb.BaseCluster.getDescription(BaseCluster.java:128)
	at com.mongodb.DBTCPConnector.getClusterDescription(DBTCPConnector.java:402)
	at com.mongodb.DBTCPConnector.getType(DBTCPConnector.java:584)
	at com.mongodb.DBTCPConnector.isMongosConnection(DBTCPConnector.java:376)
	at com.mongodb.Mongo.isMongosConnection(Mongo.java:622)
	at com.mongodb.DBCursor._check(DBCursor.java:494)
	at com.mongodb.DBCursor._hasNext(DBCursor.java:621)
	at com.mongodb.DBCursor.hasNext(DBCursor.java:657)
	at org.springframework.data.mongodb.core.MongoTemplate.executeFindMultiInternal(MongoTemplate.java:1918)
	... 35 more
The command '/bin/sh -c java ${MEMORY_USE} -Dols.home=/opt/OLS -jar /opt/OLS/ols-apps/ols-loading-app/target/ols-indexer.jar' returned a non-zero code: 1

**Comment by udp** [comment]
Hi, we are currently in the process of refactoring the OLS docker images to resolve a number of issues.  This work should be completed very soon (likely tomorrow), after which I will update the docker instructions accordingly.

**Comment by DSRYU** [comment]
Thanks for your effort to update docker instruction.

Could you let me know how I could get the updated version when you have done?

**Comment by udp** [comment]
Hi, you can find the updated Docker instructions in the docker-refactoring branch:

https://github.com/EBISPOT/OLS/tree/docker-refactoring

Please let me know how it goes!

**Comment by DSRYU** [comment]
Hello

Thank you for your refactoring git repository information.

I think the ols refactoring version you addressed has installed without any problem with just only "docker-compose up" command. It was amazing.
And I checked docker process and api calling is working as belows:

dongsung.ryu@DongSungui-MacBookPro:~/sources/OLS/OLS_working/OLS-docker-refactoring/ols-apps/ols-config-importer:> docker ps
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS              PORTS                      NAMES
9241238efc51        ols-docker-refactoring_ols-web   "java -jar /opt/ols-…"   14 minutes ago      Up 14 minutes       0.0.0.0:8080->8080/tcp     ols-docker-refactoring_ols-web_1
f7ae3461f48c        mongo:3.6.18-xenial              "docker-entrypoint.s…"   14 minutes ago      Up 14 minutes       0.0.0.0:27017->27017/tcp   ols-docker-refactoring_mongo_1
85e987d8b610        solr:5.5.3-alpine                "docker-entrypoint.s…"   14 minutes ago      Up 14 minutes       0.0.0.0:8983->8983/tcp     ols-docker-refactoring_solr_1


dongsung.ryu@DongSungui-MacBookPro:~/sources/OLS/OLS_working/OLS-docker-refactoring/ols-apps/ols-config-importer:> curl -L 'http://localhost:8080/api' -i -H 'Accept: application/json'
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
X-Application-Context: application:8080
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Wed, 17 Jun 2020 00:43:41 GMT

{
  "_links" : {
    "properties" : {
      "href" : "http://localhost:8080/api/properties"
    },
    "terms" : {
      "href" : "http://localhost:8080/api/terms"
    },
    "ontologies" : {
      "href" : "http://localhost:8080/api/ontologies"
    },
    "individuals" : {
      "href" : "http://localhost:8080/api/individuals"
    },
    "profile" : {
      "href" : "http://localhost:8080/api/profile"
    }
  }
  
 Our goal is to use duo (data use ontology) on research purpose in our system.
In order to use duo(Data Usage Ontology), I think we need to put duo structure into mongo db.
If you don't mind, could you give me some instruction which is proper to your refactoring source on docker?

Thanks.

DongSung, Ryu

**Comment by udp** [comment]
Hello, I just resolved some issues with the docker configuration, so please pull again from git.
The changes are now merged into the master branch.

The instructions for getting data into OLS using the config importer and indexer are in the readme,
under "Deploying with Docker".

If you only want DUO, edit config/ols-config.yaml and delete all the ontologies, such that the file is empty:

```
"@context":

ontologies:
```

You don't need to edit config/obo-config.yaml, as the default file already contains only DUO.

**Comment by DSRYU** [comment]
Thank you!.

It's working!

**Comment by matentzn** [comment]
@DSRYU I am trying to get a sense of custom OLS installation across the web; is yours public by any chance?
