### ISSUE TITLE
Issue with fbbt loading ref fbbt:http://flybase.org/reports/FBtp0058497

### ISSUE THREAD

**Issue by Robbie1977** [EBISPOT/OLS#4]
Getting an error when loading fbbt with the latest version:
```
2015-07-22 17:24:56.252  INFO 18487 --- [           main] .b.l.ClasspathLoggingApplicationListener : Application failed to start with classpath: [jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/ols-solr-3.0.0-SNAPSHOT.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/spring-boot-starter-data-solr-1.3.0.M1.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/spring-boot-starter-1.3.0.M1.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/spring-boot-1.3.0.M1.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/spring-boot-autoconfigure-1.3.0.M1.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/spring-boot-starter-logging-1.3.0.M1.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/logback-classic-1.1.3.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/logback-core-1.1.3.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/jul-to-slf4j-1.7.12.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/log4j-over-slf4j-1.7.12.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/spring-core-4.2.0.RC1.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/snakeyaml-1.15.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/solr-solrj-4.10.4.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/commons-io-2.3.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/httpclient-4.5.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/httpcore-4.4.1.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/zookeeper-3.4.6.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/wstx-asl-3.2.7.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/noggit-0.5.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/slf4j-api-1.7.12.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/spring-data-solr-1.5.0.M1.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/spring-context-4.2.0.RC1.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/spring-aop-4.2.0.RC1.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/aopalliance-1.0.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/spring-beans-4.2.0.RC1.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/spring-expression-4.2.0.RC1.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/spring-tx-4.2.0.RC1.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/spring-data-commons-1.11.0.M1.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/commons-lang3-3.1.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/commons-collections-3.2.1.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/httpclient-cache-4.2.2.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/jackson-databind-2.5.4.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/jackson-annotations-2.5.4.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/jcl-over-slf4j-1.7.12.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/httpmime-4.5.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/ols-core-3.0.0-SNAPSHOT.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/spring-boot-starter-data-mongodb-1.3.0.M1.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/mongo-java-driver-2.13.2.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/spring-data-mongodb-1.8.0.M1.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/ontology-tools-3.0.0-SNAPSHOT.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/owlapi-distribution-3.5.2.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/owlapi-apibinding-3.5.2.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/org.osgi.core-1.4.0.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/owlapi-api-3.5.2.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/owlapi-tools-3.5.2.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/owlapi-impl-3.5.2.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/owlapi-parsers-3.5.2.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/owlapi-oboformat-3.5.2.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/trove4j-3.0.3.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/guava-18.0.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/org.semanticweb.hermit-1.3.8.4.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/commons-logging-1.1.3.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/axiom-api-1.2.14.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/geronimo-activation_1.1_spec-1.1.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/geronimo-javamail_1.4_spec-1.7.1.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/jaxen-1.1.6.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/geronimo-stax-api_1.0_spec-1.0.1.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/apache-mime4j-core-0.7.2.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/axiom-c14n-1.2.14.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/axiom-impl-1.2.14.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/woodstox-core-asl-4.1.4.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/stax2-api-3.1.1.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/axiom-dom-1.2.14.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/automaton-1.11-8.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/elk-owlapi-0.4.2.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/elk-owl-model-0.4.2.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/elk-owl-implementation-0.4.2.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/elk-util-hashing-0.4.2.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/elk-reasoner-0.4.2.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/elk-util-collections-0.4.2.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/elk-util-concurrent-0.4.2.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/elk-util-common-0.4.2.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/elk-util-io-0.4.2.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/elk-util-logging-0.4.2.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/log4j-1.2.17.jar!/, jar:file:/amd/nfs/bocian/disk/data/ols/ols-apps/ols-solr-app/target/ols-solr-app.jar!/lib/jackson-core-2.5.4.jar!/]
2015-07-22 17:24:56.260 ERROR 18487 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.runCommandLineRunners(SpringApplication.java:667)
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:682)
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:340)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:274)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:931)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:920)
	at uk.ac.ebi.spot.ols.OntologySolrApplication.main(OntologySolrApplication.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.data.solr.UncategorizedSolrException: [doc=fbbt:http://flybase.org/reports/FBtp0058497] missing required field: bbop_sibling_graph_json; nested exception is org.apache.solr.client.solrj.impl.HttpSolrServer$RemoteSolrException: [doc=fbbt:http://flybase.org/reports/FBtp0058497] missing required field: bbop_sibling_graph_json
	at org.springframework.data.solr.core.SolrTemplate.execute(SolrTemplate.java:145)
	at org.springframework.data.solr.core.SolrTemplate.saveBeans(SolrTemplate.java:199)
	at org.springframework.data.solr.core.SolrTemplate.saveBeans(SolrTemplate.java:194)
	at org.springframework.data.solr.repository.support.SimpleSolrRepository.save(SimpleSolrRepository.java:163)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.executeMethodOn(RepositoryFactorySupport.java:452)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:437)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:409)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy35.save(Unknown Source)
	at uk.ac.ebi.spot.ols.indexer.SolrIndexer.index(SolrIndexer.java:116)
	at uk.ac.ebi.spot.ols.indexer.SolrIndexer.createIndex(SolrIndexer.java:65)
	at uk.ac.ebi.spot.ols.indexer.SolrIndexer.createIndex(SolrIndexer.java:127)
	at uk.ac.ebi.spot.ols.OntologySolrApplication.run(OntologySolrApplication.java:35)
	at org.springframework.boot.SpringApplication.runCommandLineRunners(SpringApplication.java:664)
	... 12 common frames omitted
Caused by: org.apache.solr.client.solrj.impl.HttpSolrServer$RemoteSolrException: [doc=fbbt:http://flybase.org/reports/FBtp0058497] missing required field: bbop_sibling_graph_json
	at org.apache.solr.client.solrj.impl.HttpSolrServer.executeMethod(HttpSolrServer.java:552)
	at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:210)
	at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:206)
	at org.apache.solr.client.solrj.request.AbstractUpdateRequest.process(AbstractUpdateRequest.java:124)
	at org.apache.solr.client.solrj.SolrServer.add(SolrServer.java:68)
	at org.springframework.data.solr.core.SolrTemplate$5.doInSolr(SolrTemplate.java:202)
	at org.springframework.data.solr.core.SolrTemplate$5.doInSolr(SolrTemplate.java:199)
	at org.springframework.data.solr.core.SolrTemplate.execute(SolrTemplate.java:141)
	... 38 common frames omitted

java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.runCommandLineRunners(SpringApplication.java:667)
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:682)
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:340)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:274)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:931)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:920)
	at uk.ac.ebi.spot.ols.OntologySolrApplication.main(OntologySolrApplication.java:39)
	... 6 more
Caused by: org.springframework.data.solr.UncategorizedSolrException: [doc=fbbt:http://flybase.org/reports/FBtp0058497] missing required field: bbop_sibling_graph_json; nested exception is org.apache.solr.client.solrj.impl.HttpSolrServer$RemoteSolrException: [doc=fbbt:http://flybase.org/reports/FBtp0058497] missing required field: bbop_sibling_graph_json
	at org.springframework.data.solr.core.SolrTemplate.execute(SolrTemplate.java:145)
	at org.springframework.data.solr.core.SolrTemplate.saveBeans(SolrTemplate.java:199)
	at org.springframework.data.solr.core.SolrTemplate.saveBeans(SolrTemplate.java:194)
	at org.springframework.data.solr.repository.support.SimpleSolrRepository.save(SimpleSolrRepository.java:163)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.executeMethodOn(RepositoryFactorySupport.java:452)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:437)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:409)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy35.save(Unknown Source)
	at uk.ac.ebi.spot.ols.indexer.SolrIndexer.index(SolrIndexer.java:116)
	at uk.ac.ebi.spot.ols.indexer.SolrIndexer.createIndex(SolrIndexer.java:65)
	at uk.ac.ebi.spot.ols.indexer.SolrIndexer.createIndex(SolrIndexer.java:127)
	at uk.ac.ebi.spot.ols.OntologySolrApplication.run(OntologySolrApplication.java:35)
	at org.springframework.boot.SpringApplication.runCommandLineRunners(SpringApplication.java:664)
	... 12 more
Caused by: org.apache.solr.client.solrj.impl.HttpSolrServer$RemoteSolrException: [doc=fbbt:http://flybase.org/reports/FBtp0058497] missing required field: bbop_sibling_graph_json
	at org.apache.solr.client.solrj.impl.HttpSolrServer.executeMethod(HttpSolrServer.java:552)
	at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:210)
	at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:206)
	at org.apache.solr.client.solrj.request.AbstractUpdateRequest.process(AbstractUpdateRequest.java:124)
	at org.apache.solr.client.solrj.SolrServer.add(SolrServer.java:68)
	at org.springframework.data.solr.core.SolrTemplate$5.doInSolr(SolrTemplate.java:202)
	at org.springframework.data.solr.core.SolrTemplate$5.doInSolr(SolrTemplate.java:199)
	at org.springframework.data.solr.core.SolrTemplate.execute(SolrTemplate.java:141)
	... 38 more
2015-07-22 17:24:56.265  INFO 18487 --- [       Thread-2] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@48b3d203: startup date [Wed Jul 22 17:23:11 BST 2015]; root of context hierarchy
```

**Comment by simonjupp** [comment]
bbop_sibling_graph_json has been removed from the schema. You might need to refresh your solr instance with the latest schema.
