### ISSUE TITLE
Running ols-neo4j-app fails on all properties files

### ISSUE THREAD

**Issue by jheckman-rt** [EBISPOT/OLS#464]
I have built the apps using the mvn clean package command and the additional files in the build-fix folder.  This works fine (as long as I am using the master branch, the most recent release does not build successfully anymore).

However, when I run the jar file with some of the example properties files such as:
java -Xmx2g -jar -Dspring.profiles.active=go ols-apps/ols-neo4j-app/target/ols-neo4j-app.jar

I run into the following error:
2021-02-11 15:23:23,863 DEBUG Thread-7 StructuralOWLOntologyLoader.indexOntologyAnnotations - annotationPropertyIri 1 = http://purl.org/dc/elements/1.1/title
2021-02-11 15:23:23,863 DEBUG Thread-7 StructuralOWLOntologyLoader.indexOntologyAnnotations - annotationPropertyIri 1 = http://purl.org/dc/terms/license
2021-02-11 15:23:23,866 ERROR Thread-7 StructuralOWLOntologyLoader.setInitializationException - Failed to initialize StructuralOWLOntologyLoader. Initialization exception updated : null
java.lang.NullPointerException: null
	at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.indexOntologyAnnotations(AbstractOWLOntologyLoader.java:533)
	at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.loadOntology(AbstractOWLOntologyLoader.java:440)
	at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.doInitialization(AbstractOWLOntologyLoader.java:355)
	at uk.ac.ebi.spot.ols.util.Initializable$1.run(Initializable.java:147)
	at java.lang.Thread.run(Thread.java:748)
2021-02-11 15:23:23,866 ERROR Thread-7 StructuralOWLOntologyLoader.loadOntology - Failed to parse go : null
java.lang.NullPointerException: null
	at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.indexOntologyAnnotations(AbstractOWLOntologyLoader.java:533)
	at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.loadOntology(AbstractOWLOntologyLoader.java:440)
	at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.doInitialization(AbstractOWLOntologyLoader.java:355)
	at uk.ac.ebi.spot.ols.util.Initializable$1.run(Initializable.java:147)
	at java.lang.Thread.run(Thread.java:748)
2021-02-11 15:23:24,739 DEBUG Thread-7 StructuralOWLOntologyLoader.run - Caught exception whilst initializing, attempting to handle with clean termination
java.lang.NullPointerException: null
	at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.indexOntologyAnnotations(AbstractOWLOntologyLoader.java:533)
	at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.loadOntology(AbstractOWLOntologyLoader.java:440)
	at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.doInitialization(AbstractOWLOntologyLoader.java:355)
	at uk.ac.ebi.spot.ols.util.Initializable$1.run(Initializable.java:147)
	at java.lang.Thread.run(Thread.java:748)
2021-02-11 15:23:24,739 ERROR main SpringApplication.handleRunFailure - Application startup failed
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:803)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:784)
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:771)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
	at uk.ac.ebi.spot.ols.GraphLoaderApplication.main(GraphLoaderApplication.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:104)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:61)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.RuntimeException: Failed to lazily instantiate collection for query
	at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.lazyGet(AbstractOWLOntologyLoader.java:349)
	at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.getAllClasses(AbstractOWLOntologyLoader.java:1685)
	at uk.ac.ebi.spot.ols.loader.BatchNeo4JIndexer.indexClasses(BatchNeo4JIndexer.java:308)
	at uk.ac.ebi.spot.ols.loader.BatchNeo4JIndexer.createIndex(BatchNeo4JIndexer.java:437)
	at uk.ac.ebi.spot.ols.loader.BatchNeo4JIndexer.createIndex(BatchNeo4JIndexer.java:592)
	at uk.ac.ebi.spot.ols.GraphLoaderApplication.run(GraphLoaderApplication.java:40)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:800)
	... 14 common frames omitted
Caused by: java.lang.IllegalStateException: Initialization of StructuralOWLOntologyLoader failed: null
	at uk.ac.ebi.spot.ols.util.Initializable.isReady(Initializable.java:75)
	at uk.ac.ebi.spot.ols.util.Initializable.waitUntilReady(Initializable.java:88)
	at uk.ac.ebi.spot.ols.util.Initializable.initOrWait(Initializable.java:110)
	at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.lazyGet(AbstractOWLOntologyLoader.java:342)
	... 20 common frames omitted
Caused by: java.lang.NullPointerException: null
	at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.indexOntologyAnnotations(AbstractOWLOntologyLoader.java:533)
	at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.loadOntology(AbstractOWLOntologyLoader.java:440)
	at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.doInitialization(AbstractOWLOntologyLoader.java:355)
	at uk.ac.ebi.spot.ols.util.Initializable$1.run(Initializable.java:147)
	at java.lang.Thread.run(Thread.java:748)
2021-02-11 15:23:24,739 ERROR Thread-7 StructuralOWLOntologyLoader.setInitializationException - Failed to initialize StructuralOWLOntologyLoader. Initialization exception updated : null
java.lang.NullPointerException: null
	at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.indexOntologyAnnotations(AbstractOWLOntologyLoader.java:533)
	at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.loadOntology(AbstractOWLOntologyLoader.java:440)
	at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.doInitialization(AbstractOWLOntologyLoader.java:355)
	at uk.ac.ebi.spot.ols.util.Initializable$1.run(Initializable.java:147)
	at java.lang.Thread.run(Thread.java:748)
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:62)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:104)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:61)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
	... 3 more
Caused by: java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:803)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:784)
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:771)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
	at uk.ac.ebi.spot.ols.GraphLoaderApplication.main(GraphLoaderApplication.java:47)
	... 8 more
Caused by: java.lang.RuntimeException: Failed to lazily instantiate collection for query
	at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.lazyGet(AbstractOWLOntologyLoader.java:349)
	at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.getAllClasses(AbstractOWLOntologyLoader.java:1685)
	at uk.ac.ebi.spot.ols.loader.BatchNeo4JIndexer.indexClasses(BatchNeo4JIndexer.java:308)
	at uk.ac.ebi.spot.ols.loader.BatchNeo4JIndexer.createIndex(BatchNeo4JIndexer.java:437)
	at uk.ac.ebi.spot.ols.loader.BatchNeo4JIndexer.createIndex(BatchNeo4JIndexer.java:592)
	at uk.ac.ebi.spot.ols.GraphLoaderApplication.run(GraphLoaderApplication.java:40)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:800)
	... 14 more
Caused by: java.lang.IllegalStateException: Initialization of StructuralOWLOntologyLoader failed: null
	at uk.ac.ebi.spot.ols.util.Initializable.isReady(Initializable.java:75)
	at uk.ac.ebi.spot.ols.util.Initializable.waitUntilReady(Initializable.java:88)
	at uk.ac.ebi.spot.ols.util.Initializable.initOrWait(Initializable.java:110)
	at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.lazyGet(AbstractOWLOntologyLoader.java:342)
	... 20 more
Caused by: java.lang.NullPointerException
	at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.indexOntologyAnnotations(AbstractOWLOntologyLoader.java:533)
	at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.loadOntology(AbstractOWLOntologyLoader.java:440)
	at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.doInitialization(AbstractOWLOntologyLoader.java:355)
	at uk.ac.ebi.spot.ols.util.Initializable$1.run(Initializable.java:147)
	at java.lang.Thread.run(Thread.java:748)

In fact, I run into this exact same error when I try to run this command for ALL the sample properties files AND for any file I've tried to generate myself.  

I've attached the full output of the logs printed to the screen in the output.txt file.
[output.txt](https://github.com/EBISPOT/OLS/files/5968539/output.txt)

Please help!  Thank you!

**Comment by henrietteharmse** [comment]
Unfortunately I have to admit that the Neo4J app (and Solr app) is not well maintained nor well tested. In general the indexer (/ols-indexer) is used to index ontologies rather than the apps. 

Can you provide a minimal ontology that we can use to try and reproduce the error?

**Comment by jheckman-rt** [comment]
There's not great documentation on how to set up the properties files (ie what all the parameters mean) so your best bet is to try with the properties files that the app identifies as examples.  This is an examples of one: https://github.com/EBISPOT/OLS/blob/master/ols-apps/ols-neo4j-app/src/main/resources/application-go.properties
