### ISSUE TITLE
Errors during ontology indexing/ Ontology of units of measure

### ISSUE THREAD

**Issue by SArndt-TIB** [EBISPOT/OLS#477]
Hi everyone, at [TIB](www.tib.eu) we are currently trying to populate our instance of OLS with ontologies.

Trying to index the [Ontology of Units of Measure (OM)](https://raw.githubusercontent.com/HajoRijgersberg/OM/master/om-2.0.rdf) fails, though, resulting in the ontology not being loaeded to the ols-web:

![grafik](https://user-images.githubusercontent.com/52701352/117140108-4f851000-adad-11eb-840f-3f6b8a5b16fb.png)

The error during indexing is:
```
2021-05-03 10:05:37,373 ERROR main MongoOntologyIndexingService.indexOntologyDocument - Error indexing om
java.util.NoSuchElementException: No value present
at java.util.Optional.get(Optional.java:135)
at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.getShortForm(AbstractOWLOntologyLoader.java:319)
at uk.ac.ebi.spot.ols.indexer.SolrIndexer.extractFeatures(SolrIndexer.java:249)
at uk.ac.ebi.spot.ols.indexer.SolrIndexer.createIndex(SolrIndexer.java:124)
at uk.ac.ebi.spot.ols.indexer.SolrIndexer.createIndex(SolrIndexer.java:197)
at uk.ac.ebi.spot.ols.service.MongoOntologyIndexingService.indexOntologyDocument(MongoOntologyIndexingService.java:106)
at uk.ac.ebi.spot.ols.LoadingApplication.run(LoadingApplication.java:180)
at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:800)
at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:784)
at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:771)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
at uk.ac.ebi.spot.ols.LoadingApplication.main(LoadingApplication.java:303)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:104)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:61)
at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
```

Since the same ontology has been loaded successefully to the Ontology Look-up service and has also been updated recently (https://www.ebi.ac.uk/ols/api/ontologies/om), we were wondering, whether you have an idea how to fix this?

Could for example something be missing in our config file and the metadata?
```yaml
- ontology_purl: https://raw.githubusercontent.com/HajoRijgersberg/OM/master/om-2.0.rdf
  contact:
    github: HajoRijgersberg
    label: Hajo Rijgersberg
  description: The Ontology of units of Measure (OM) 2.0 models concepts and relations important to scientific research. It has a strong focus on units, quantities, measurements, and dimensions.
  id: om
  in_foundry_order: 0
  layout: ontology_detail
  license:
    label: CC-BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  title: Ontology of units of Measure (OM)
  tracker: https://github.com/HajoRijgersberg/OM/issues
  definition_property:
    - http://www.w3.org/2000/01/rdf-schema#comment
  creator:
    - Hajo Rijgersberg
    - Don Willems
    - Jan Top
  is_foundary: 0
  preferredPrefix: OM
  label_property: http://www.w3.org/2000/01/rdf-schema#label
  synonym_property:
    - http://www.ontology-of-units-of-measure.org/resource/om-2/alternativeLabel
  homepage: https://github.com/HajoRijgersberg/OM
  mailing_list: hajo.rijgersberg@wur.nl
```

Should we maybe add a value to the config key `base_url` (e.g. http://www.wurvoc.org/vocabularies/om-2.0/
).

We would appreciate any advice you might have. Thanks for your support!

Susanne

**Comment by udp** [comment]
Hi, we are looking into this as we have the same issue with another ontology as of today. I'll keep you informed.

**Comment by udp** [comment]
Actually seems the issue we have with the other ontology is unrelated.

Here is the config we are using for OM:

```
  - id: om
    preferredPrefix: OM
    title: Ontology of units of Measure (OM)
    uri: http://www.wurvoc.org/vocabularies/om-2.0/
    description: "The OM ontology provides classes, instances, and properties that represent the different concepts used for defining and using measures and units. It includes, for instance, common units such as the SI units meter and kilogram, but also units from other systems of units such as the mile or nautical mile. For many application areas it includes more specific units and quantities, such as the unit of the Hubble constant: km/s/Mpc, or the quantity vaselife.  OM defines the complete set of concepts in the domain as distinguished in the textual standards. As a result the ontology can answer a wider range of competency questions than the existing approaches do. The following application areas are supported by OM:  Geometry; Mechanics; Thermodynamics; Electromagnetism; Fluid mechanics; Chemical physics; Photometry; Radiometry and Radiobiology; Nuclear physics; Astronomy and Astrophysics; Cosmology; Earth science; Meteorology; Material science; Microbiology; Economics; Information technology; Typography; Shipping; Food engineering; Post-harvest; technology; Dynamics of texture and taste; Packaging"
    homepage: https://github.com/HajoRijgersberg/OM
    mailing_list: hajo.rijgersberg@wur.nl
    definition_property:
      - http://purl.obolibrary.org/obo/IAO_0000115
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    hierarchical_property:
      - http://purl.obolibrary.org/obo/BFO_0000050
      - http://purl.obolibrary.org/obo/RO_0002202
    hidden_property:
      - http://www.ebi.ac.uk/efo/has_flag
    base_uri:
      - http://www.wurvoc.org/vocabularies/om-2.0/
    reasoner: EL
    oboSlims: false
    ontology_purl : https://raw.githubusercontent.com/HajoRijgersberg/OM/master/om-2.0.rdf
```

**Comment by SArndt-TIB** [comment]
Thanks for sharing your metadata :-) I used them for another try, but it did not turn out as we had hoped:

```json
{
  "ontologyId" : "om",
  "loaded" : null,
  "updated" : "2021-05-05T14:10:24.029+0000",
  "status" : "FAILED",
  "message" : "No value present",
  "version" : null,
  "fileHash" : "23905a9b54dac3e9a7f8990e4fef998ea05b6040",
  "loadAttempts" : 0,
  "numberOfTerms" : 0,
  "numberOfProperties" : 0,
  "numberOfIndividuals" : 0,
  "config" : {
    "id" : "http://www.wurvoc.org/vocabularies/om-2.0/",
    "versionIri" : null,
    "title" : "Ontology of units of Measure (OM)",
    "namespace" : "om",
    "preferredPrefix" : "OM",
    "description" : "The OM ontology provides classes, instances, and properties that represent the different concepts used for defining and using measures and units. It includes, for instance, common units such as the SI units meter and kilogram, but also units from other systems of units such as the mile or nautical mile. For many application areas it includes more specific units and quantities, such as the unit of the Hubble constant: km/s/Mpc, or the quantity vaselife.  OM defines the complete set of concepts in the domain as distinguished in the textual standards. As a result the ontology can answer a wider range of competency questions than the existing approaches do. The following application areas are supported by OM:  Geometry; Mechanics; Thermodynamics; Electromagnetism; Fluid mechanics; Chemical physics; Photometry; Radiometry and Radiobiology; Nuclear physics; Astronomy and Astrophysics; Cosmology; Earth science; Meteorology; Material science; Microbiology; Economics; Information technology; Typography; Shipping; Food engineering; Post-harvest; technology; Dynamics of texture and taste; Packaging",
    "homepage" : "https://github.com/HajoRijgersberg/OM",
    "version" : null,
    "mailingList" : "hajo.rijgersberg@wur.nl",
    "creators" : [ ],
    "annotations" : { },
    "fileLocation" : "https://raw.githubusercontent.com/HajoRijgersberg/OM/master/om-2.0.rdf",
    "reasonerType" : "EL",
    "oboSlims" : false,
    "labelProperty" : "http://www.w3.org/2000/01/rdf-schema#label",
    "definitionProperties" : [ "http://purl.obolibrary.org/obo/IAO_0000115" ],
    "synonymProperties" : [ "http://www.geneontology.org/formats/oboInOwl#hasExactSynonym" ],
    "hierarchicalProperties" : [ "http://purl.obolibrary.org/obo/RO_0002202", "http://purl.obolibrary.org/obo/BFO_0000050" ],
    "baseUris" : [ "http://www.wurvoc.org/vocabularies/om-2.0/" ],
    "hiddenProperties" : [ "http://www.ebi.ac.uk/efo/has_flag" ],
    "preferredRootTerms" : [ ],
    "allowDownload" : true,
    "subjects" : null,
    "internalMetadataProperties" : [ ],
    "skos" : false
  },
  "_links" : {
    "self" : {
      "href" : "http://terminology02.develop.service.tib.eu:8080/ts4tib/api/ontologies/om"
    },
    "terms" : {
      "href" : "http://terminology02.develop.service.tib.eu:8080/ts4tib/api/ontologies/om/terms"
    },
    "properties" : {
      "href" : "http://terminology02.develop.service.tib.eu:8080/ts4tib/api/ontologies/om/properties"
    },
    "individuals" : {
      "href" : "http://terminology02.develop.service.tib.eu:8080/ts4tib/api/ontologies/om/individuals"
    }
  }
}
```

If anything turns up, I'll give an update here. Thank you so much!
