### ISSUE TITLE
Load custom ontology from local file

### ISSUE THREAD

**Issue by rpandey19** [EBISPOT/OLS#484]
How can we load a custom ontology from a local file. I have setup the local installation of OLS but when I try to provide the path for a local owl / obo file in the config it gives me argument exception
java.lang.IllegalArgumentException: Illegal character in opaque part at index 2: fulllocalpath\config\ref_assay.owl
        at java.net.URI.create(URI.java:852)
        at uk.ac.ebi.spot.ols.config.YamlBasedLoadingService.getOntologyPURL(YamlBasedLoadingService.java:253)
        at uk.ac.ebi.spot.ols.config.YamlBasedLoadingService.getConfiguration(YamlBasedLoadingService.java:48)
        at uk.ac.ebi.spot.ols.YamlLoader.updateDocument(YamlLoader.java:88)
        at uk.ac.ebi.spot.ols.YamlLoader.run(YamlLoader.java:76)

**Comment by matentzn** [comment]
Here is an example:
https://github.com/monarch-initiative/ols_monarch/blob/master/ols/ols-config.yaml

Does this way of doing it work for you?

**Comment by matentzn** [comment]
Can you share your config?

**Comment by rpandey19** [comment]
I got it working but setting a httpd container and hosting the file in it. 
But this is how I used it and the error I got-
- id: refassay2
    preferredPrefix: REFASSAY2
    ontology_purl: file://Users/user/dev/work/test/ref_assay0.owl
    title: Custom Assay Ontology 2
    description: "Custom testing ontology 2"

Error-
FileUpdatingService.run - Error checking: Custom Assay Ontology 2Failed to download file: sun.net.www.protocol.ftp.FtpURLConnection cannot be cast to java.net.HttpURLConnection
uk.ac.ebi.spot.ols.exception.FileUpdateServiceException: Failed to download file: sun.net.www.protocol.ftp.FtpURLConnection cannot be cast to java.net.HttpURLConnection
	at uk.ac.ebi.spot.ols.util.FileUpdater.getFile(FileUpdater.java:138)

**Comment by matentzn** [comment]
could it have been one too many slashes after the `file:`?, i.e.:

```
ontology_purl: file:/Users/user/dev/work/test/ref_assay0.owl
```

[That](https://github.com/monarch-initiative/ols_monarch/blob/861d1cd71c48e66ba9c1c51fa80975da315ab86d/ols/ols-config.yaml#L23) worked for me.

**Comment by rpandey19** [comment]
It still fails. I just tried it. The indexer fails. It seems to be looking for http url.
When I host the file on server it works fine.

BTW by any chance have you tried the OXO installation with docker? I am having trouble with that installation

**Comment by henrietteharmse** [comment]
@rpandey19 Have you been to resolve the issues you experienced with OLS and OxO installations?
