### ISSUE TITLE
findByIdAndIsDefiningOntology API call seems to be failing

### ISSUE THREAD

**Issue by bherr2** [EBISPOT/OLS#558]
This used to work: <https://www.ebi.ac.uk/ols/api/terms/findByIdAndIsDefiningOntology?obo_id=UBERON:0001516> has the API changed?

**Comment by henrietteharmse** [comment]
Thanks for bringing this to our attention! We will have this fixed on Monday!

**Comment by henrietteharmse** [comment]
Here is the related stack trace:

2022-02-18 15:16:54.139 ERROR 4891 --- [http-bio-8080-exec-5] o.s.boot.context.web.ErrorPageFilter     : Forwarding to error page from request [/api/terms/findByIdAndIsDefiningOntology] due to exception [uk.ac.ebi.spot.ols.neo4j.model.Term cannot be cast to uk.ac.ebi.spot.ols.controller.api.localization.LocalizedTerm]

java.lang.ClassCastException: uk.ac.ebi.spot.ols.neo4j.model.Term cannot be cast to uk.ac.ebi.spot.ols.controller.api.localization.LocalizedTerm
        at uk.ac.ebi.spot.ols.controller.api.TermAssembler.toResource(TermAssembler.java:24)
        at org.springframework.data.web.PagedResourcesAssembler.createResource(PagedResourcesAssembler.java:182)
        at org.springframework.data.web.PagedResourcesAssembler.toResource(PagedResourcesAssembler.java:115)
        at uk.ac.ebi.spot.ols.controller.api.TermController.getTermsByIdAndIsDefiningOntology(TermController.java:161)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by jamesamcl** [comment]
Hi, this is fixed now! thanks

**Comment by bherr2** [comment]
Thank you!
